---
driver:
  name: azurerm
  subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
  location: 'South Central US'
  machine_size: Standard_D2
  
transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 2
  wait_for_retry: 90

platforms:
  - name: win2012r2
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest

suites:
  - name: default
    run_list:
      - recipe[minimal::default]
  - name: ciminstance
    run_list:
      - recipe[minimal::ciminstance]
